package co.edu.unicauca.appterapiademencia.domain;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "DETAIL_FAST".
 */
@Entity
public class DetailFast {

    @Id(autoincrement = true)
    private Long id;
    private long escalaId;
    private String stagename;
    private String characteristics;
    private String mentalage;
    private String mmsescore;

    @Generated
    public DetailFast() {
    }

    public DetailFast(Long id) {
        this.id = id;
    }

    @Generated
    public DetailFast(Long id, long escalaId, String stagename, String characteristics, String mentalage, String mmsescore) {
        this.id = id;
        this.escalaId = escalaId;
        this.stagename = stagename;
        this.characteristics = characteristics;
        this.mentalage = mentalage;
        this.mmsescore = mmsescore;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getEscalaId() {
        return escalaId;
    }

    public void setEscalaId(long escalaId) {
        this.escalaId = escalaId;
    }

    public String getStagename() {
        return stagename;
    }

    public void setStagename(String stagename) {
        this.stagename = stagename;
    }

    public String getCharacteristics() {
        return characteristics;
    }

    public void setCharacteristics(String characteristics) {
        this.characteristics = characteristics;
    }

    public String getMentalage() {
        return mentalage;
    }

    public void setMentalage(String mentalage) {
        this.mentalage = mentalage;
    }

    public String getMmsescore() {
        return mmsescore;
    }

    public void setMmsescore(String mmsescore) {
        this.mmsescore = mmsescore;
    }

}
