package co.edu.unicauca.appterapiademencia.domain;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "HISTORIC".
 */
@Entity
public class Historic {

    @Id(autoincrement = true)
    private Long id;
    private long patientId;
    private long exerciseId;
    private java.util.Date date;
    private String hour;
    private Boolean completed;

    @Generated
    public Historic() {
    }

    public Historic(Long id) {
        this.id = id;
    }

    @Generated
    public Historic(Long id, long patientId, long exerciseId, java.util.Date date, String hour, Boolean completed) {
        this.id = id;
        this.patientId = patientId;
        this.exerciseId = exerciseId;
        this.date = date;
        this.hour = hour;
        this.completed = completed;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getPatientId() {
        return patientId;
    }

    public void setPatientId(long patientId) {
        this.patientId = patientId;
    }

    public long getExerciseId() {
        return exerciseId;
    }

    public void setExerciseId(long exerciseId) {
        this.exerciseId = exerciseId;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

    public String getHour() {
        return hour;
    }

    public void setHour(String hour) {
        this.hour = hour;
    }

    public Boolean getCompleted() {
        return completed;
    }

    public void setCompleted(Boolean completed) {
        this.completed = completed;
    }

}
