package co.edu.unicauca.appterapiademencia.domain;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "PHYSIC".
 */
@Entity
public class Physic {

    @Id(autoincrement = true)
    private Long id;
    private String type;
    private long patientId;

    @Generated
    public Physic() {
    }

    public Physic(Long id) {
        this.id = id;
    }

    @Generated
    public Physic(Long id, String type, long patientId) {
        this.id = id;
        this.type = type;
        this.patientId = patientId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public long getPatientId() {
        return patientId;
    }

    public void setPatientId(long patientId) {
        this.patientId = patientId;
    }

}
