package co.edu.unicauca.appterapiademencia.domain;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "PREFERENCE_TIP".
 */
@Entity
public class PreferenceTip {

    @Id(autoincrement = true)
    private Long id;
    private long userId;
    private long tipId;
    private Boolean favorite;

    @Generated
    public PreferenceTip() {
    }

    public PreferenceTip(Long id) {
        this.id = id;
    }

    @Generated
    public PreferenceTip(Long id, long userId, long tipId, Boolean favorite) {
        this.id = id;
        this.userId = userId;
        this.tipId = tipId;
        this.favorite = favorite;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getUserId() {
        return userId;
    }

    public void setUserId(long userId) {
        this.userId = userId;
    }

    public long getTipId() {
        return tipId;
    }

    public void setTipId(long tipId) {
        this.tipId = tipId;
    }

    public Boolean getFavorite() {
        return favorite;
    }

    public void setFavorite(Boolean favorite) {
        this.favorite = favorite;
    }

}
