package co.edu.unicauca.appterapiademencia.domain;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "RECOMMENDATION".
 */
@Entity
public class Recommendation {

    @Id(autoincrement = true)
    private Long id;
    private long patientId;
    private long exerciseId;

    @Generated
    public Recommendation() {
    }

    public Recommendation(Long id) {
        this.id = id;
    }

    @Generated
    public Recommendation(Long id, long patientId, long exerciseId) {
        this.id = id;
        this.patientId = patientId;
        this.exerciseId = exerciseId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getPatientId() {
        return patientId;
    }

    public void setPatientId(long patientId) {
        this.patientId = patientId;
    }

    public long getExerciseId() {
        return exerciseId;
    }

    public void setExerciseId(long exerciseId) {
        this.exerciseId = exerciseId;
    }

}
