package co.edu.unicauca.appterapiademencia.domain;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "SCALE".
 */
@Entity
public class Scale {

    @Id(autoincrement = true)
    private Long id;
    private long sintomaId;
    private String escalaname;
    private String puntaje;

    @Generated
    public Scale() {
    }

    public Scale(Long id) {
        this.id = id;
    }

    @Generated
    public Scale(Long id, long sintomaId, String escalaname, String puntaje) {
        this.id = id;
        this.sintomaId = sintomaId;
        this.escalaname = escalaname;
        this.puntaje = puntaje;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getSintomaId() {
        return sintomaId;
    }

    public void setSintomaId(long sintomaId) {
        this.sintomaId = sintomaId;
    }

    public String getEscalaname() {
        return escalaname;
    }

    public void setEscalaname(String escalaname) {
        this.escalaname = escalaname;
    }

    public String getPuntaje() {
        return puntaje;
    }

    public void setPuntaje(String puntaje) {
        this.puntaje = puntaje;
    }

}
