package co.edu.unicauca.appterapiademencia.domain;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "SINTOMA".
 */
@Entity
public class Sintoma {

    @Id(autoincrement = true)
    private Long id;
    private long patientId;
    private long noteId;
    private String ambito;
    private String selection;

    @Generated
    public Sintoma() {
    }

    public Sintoma(Long id) {
        this.id = id;
    }

    @Generated
    public Sintoma(Long id, long patientId, long noteId, String ambito, String selection) {
        this.id = id;
        this.patientId = patientId;
        this.noteId = noteId;
        this.ambito = ambito;
        this.selection = selection;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getPatientId() {
        return patientId;
    }

    public void setPatientId(long patientId) {
        this.patientId = patientId;
    }

    public long getNoteId() {
        return noteId;
    }

    public void setNoteId(long noteId) {
        this.noteId = noteId;
    }

    public String getAmbito() {
        return ambito;
    }

    public void setAmbito(String ambito) {
        this.ambito = ambito;
    }

    public String getSelection() {
        return selection;
    }

    public void setSelection(String selection) {
        this.selection = selection;
    }

}
