package co.edu.unicauca.appterapiademencia.domain.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import co.edu.unicauca.appterapiademencia.domain.User;
import co.edu.unicauca.appterapiademencia.domain.Patient;
import co.edu.unicauca.appterapiademencia.domain.BlessedIncapacity;
import co.edu.unicauca.appterapiademencia.domain.Note;
import co.edu.unicauca.appterapiademencia.domain.Tip;
import co.edu.unicauca.appterapiademencia.domain.Exercise;
import co.edu.unicauca.appterapiademencia.domain.Historic;
import co.edu.unicauca.appterapiademencia.domain.Recommendation;

import co.edu.unicauca.appterapiademencia.domain.dao.UserDao;
import co.edu.unicauca.appterapiademencia.domain.dao.PatientDao;
import co.edu.unicauca.appterapiademencia.domain.dao.BlessedIncapacityDao;
import co.edu.unicauca.appterapiademencia.domain.dao.NoteDao;
import co.edu.unicauca.appterapiademencia.domain.dao.TipDao;
import co.edu.unicauca.appterapiademencia.domain.dao.ExerciseDao;
import co.edu.unicauca.appterapiademencia.domain.dao.HistoricDao;
import co.edu.unicauca.appterapiademencia.domain.dao.RecommendationDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig patientDaoConfig;
    private final DaoConfig blessedIncapacityDaoConfig;
    private final DaoConfig noteDaoConfig;
    private final DaoConfig tipDaoConfig;
    private final DaoConfig exerciseDaoConfig;
    private final DaoConfig historicDaoConfig;
    private final DaoConfig recommendationDaoConfig;

    private final UserDao userDao;
    private final PatientDao patientDao;
    private final BlessedIncapacityDao blessedIncapacityDao;
    private final NoteDao noteDao;
    private final TipDao tipDao;
    private final ExerciseDao exerciseDao;
    private final HistoricDao historicDao;
    private final RecommendationDao recommendationDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        patientDaoConfig = daoConfigMap.get(PatientDao.class).clone();
        patientDaoConfig.initIdentityScope(type);

        blessedIncapacityDaoConfig = daoConfigMap.get(BlessedIncapacityDao.class).clone();
        blessedIncapacityDaoConfig.initIdentityScope(type);

        noteDaoConfig = daoConfigMap.get(NoteDao.class).clone();
        noteDaoConfig.initIdentityScope(type);

        tipDaoConfig = daoConfigMap.get(TipDao.class).clone();
        tipDaoConfig.initIdentityScope(type);

        exerciseDaoConfig = daoConfigMap.get(ExerciseDao.class).clone();
        exerciseDaoConfig.initIdentityScope(type);

        historicDaoConfig = daoConfigMap.get(HistoricDao.class).clone();
        historicDaoConfig.initIdentityScope(type);

        recommendationDaoConfig = daoConfigMap.get(RecommendationDao.class).clone();
        recommendationDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        patientDao = new PatientDao(patientDaoConfig, this);
        blessedIncapacityDao = new BlessedIncapacityDao(blessedIncapacityDaoConfig, this);
        noteDao = new NoteDao(noteDaoConfig, this);
        tipDao = new TipDao(tipDaoConfig, this);
        exerciseDao = new ExerciseDao(exerciseDaoConfig, this);
        historicDao = new HistoricDao(historicDaoConfig, this);
        recommendationDao = new RecommendationDao(recommendationDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Patient.class, patientDao);
        registerDao(BlessedIncapacity.class, blessedIncapacityDao);
        registerDao(Note.class, noteDao);
        registerDao(Tip.class, tipDao);
        registerDao(Exercise.class, exerciseDao);
        registerDao(Historic.class, historicDao);
        registerDao(Recommendation.class, recommendationDao);
    }
    
    public void clear() {
        userDaoConfig.clearIdentityScope();
        patientDaoConfig.clearIdentityScope();
        blessedIncapacityDaoConfig.clearIdentityScope();
        noteDaoConfig.clearIdentityScope();
        tipDaoConfig.clearIdentityScope();
        exerciseDaoConfig.clearIdentityScope();
        historicDaoConfig.clearIdentityScope();
        recommendationDaoConfig.clearIdentityScope();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public PatientDao getPatientDao() {
        return patientDao;
    }

    public BlessedIncapacityDao getBlessedIncapacityDao() {
        return blessedIncapacityDao;
    }

    public NoteDao getNoteDao() {
        return noteDao;
    }

    public TipDao getTipDao() {
        return tipDao;
    }

    public ExerciseDao getExerciseDao() {
        return exerciseDao;
    }

    public HistoricDao getHistoricDao() {
        return historicDao;
    }

    public RecommendationDao getRecommendationDao() {
        return recommendationDao;
    }

}
