package co.edu.unicauca.appterapiademencia.domain.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import co.edu.unicauca.appterapiademencia.domain.Patient;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PATIENT".
*/
public class PatientDao extends AbstractDao<Patient, Long> {

    public static final String TABLENAME = "PATIENT";

    /**
     * Properties of entity Patient.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Age = new Property(2, int.class, "age", false, "AGE");
        public final static Property Eps = new Property(3, Integer.class, "eps", false, "EPS");
        public final static Property Identity = new Property(4, int.class, "identity", false, "IDENTITY");
        public final static Property Antecedents = new Property(5, String.class, "antecedents", false, "ANTECEDENTS");
        public final static Property Syndromes = new Property(6, String.class, "syndromes", false, "SYNDROMES");
        public final static Property Observations = new Property(7, String.class, "observations", false, "OBSERVATIONS");
        public final static Property Mec = new Property(8, Integer.class, "mec", false, "MEC");
        public final static Property Gds = new Property(9, Integer.class, "gds", false, "GDS");
    }

    private DaoSession daoSession;


    public PatientDao(DaoConfig config) {
        super(config);
    }
    
    public PatientDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PATIENT\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"NAME\" TEXT NOT NULL ," + // 1: name
                "\"AGE\" INTEGER NOT NULL ," + // 2: age
                "\"EPS\" INTEGER," + // 3: eps
                "\"IDENTITY\" INTEGER NOT NULL UNIQUE ," + // 4: identity
                "\"ANTECEDENTS\" TEXT," + // 5: antecedents
                "\"SYNDROMES\" TEXT," + // 6: syndromes
                "\"OBSERVATIONS\" TEXT," + // 7: observations
                "\"MEC\" INTEGER," + // 8: mec
                "\"GDS\" INTEGER);"); // 9: gds
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PATIENT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Patient entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getName());
        stmt.bindLong(3, entity.getAge());
 
        Integer eps = entity.getEps();
        if (eps != null) {
            stmt.bindLong(4, eps);
        }
        stmt.bindLong(5, entity.getIdentity());
 
        String antecedents = entity.getAntecedents();
        if (antecedents != null) {
            stmt.bindString(6, antecedents);
        }
 
        String syndromes = entity.getSyndromes();
        if (syndromes != null) {
            stmt.bindString(7, syndromes);
        }
 
        String observations = entity.getObservations();
        if (observations != null) {
            stmt.bindString(8, observations);
        }
 
        Integer mec = entity.getMec();
        if (mec != null) {
            stmt.bindLong(9, mec);
        }
 
        Integer gds = entity.getGds();
        if (gds != null) {
            stmt.bindLong(10, gds);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Patient entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getName());
        stmt.bindLong(3, entity.getAge());
 
        Integer eps = entity.getEps();
        if (eps != null) {
            stmt.bindLong(4, eps);
        }
        stmt.bindLong(5, entity.getIdentity());
 
        String antecedents = entity.getAntecedents();
        if (antecedents != null) {
            stmt.bindString(6, antecedents);
        }
 
        String syndromes = entity.getSyndromes();
        if (syndromes != null) {
            stmt.bindString(7, syndromes);
        }
 
        String observations = entity.getObservations();
        if (observations != null) {
            stmt.bindString(8, observations);
        }
 
        Integer mec = entity.getMec();
        if (mec != null) {
            stmt.bindLong(9, mec);
        }
 
        Integer gds = entity.getGds();
        if (gds != null) {
            stmt.bindLong(10, gds);
        }
    }

    @Override
    protected final void attachEntity(Patient entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Patient readEntity(Cursor cursor, int offset) {
        Patient entity = new Patient( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // name
            cursor.getInt(offset + 2), // age
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // eps
            cursor.getInt(offset + 4), // identity
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // antecedents
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // syndromes
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // observations
            cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8), // mec
            cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9) // gds
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Patient entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.getString(offset + 1));
        entity.setAge(cursor.getInt(offset + 2));
        entity.setEps(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setIdentity(cursor.getInt(offset + 4));
        entity.setAntecedents(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setSyndromes(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setObservations(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setMec(cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8));
        entity.setGds(cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Patient entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Patient entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Patient entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
