package co.edu.unicauca.appterapiademencia.domain.dao;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import co.edu.unicauca.appterapiademencia.domain.Sintoma;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SINTOMA".
*/
public class SintomaDao extends AbstractDao<Sintoma, Long> {

    public static final String TABLENAME = "SINTOMA";

    /**
     * Properties of entity Sintoma.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property PatientId = new Property(1, long.class, "patientId", false, "PATIENT_ID");
        public final static Property Ambito = new Property(2, String.class, "ambito", false, "AMBITO");
        public final static Property Signo = new Property(3, String.class, "signo", false, "SIGNO");
        public final static Property Activo = new Property(4, Boolean.class, "activo", false, "ACTIVO");
    }

    private DaoSession daoSession;

    private Query<Sintoma> patient_SintomaListQuery;

    public SintomaDao(DaoConfig config) {
        super(config);
    }
    
    public SintomaDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SINTOMA\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"PATIENT_ID\" INTEGER NOT NULL ," + // 1: patientId
                "\"AMBITO\" TEXT," + // 2: ambito
                "\"SIGNO\" TEXT," + // 3: signo
                "\"ACTIVO\" INTEGER);"); // 4: activo
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SINTOMA\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Sintoma entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getPatientId());
 
        String ambito = entity.getAmbito();
        if (ambito != null) {
            stmt.bindString(3, ambito);
        }
 
        String signo = entity.getSigno();
        if (signo != null) {
            stmt.bindString(4, signo);
        }
 
        Boolean activo = entity.getActivo();
        if (activo != null) {
            stmt.bindLong(5, activo ? 1L: 0L);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Sintoma entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getPatientId());
 
        String ambito = entity.getAmbito();
        if (ambito != null) {
            stmt.bindString(3, ambito);
        }
 
        String signo = entity.getSigno();
        if (signo != null) {
            stmt.bindString(4, signo);
        }
 
        Boolean activo = entity.getActivo();
        if (activo != null) {
            stmt.bindLong(5, activo ? 1L: 0L);
        }
    }

    @Override
    protected final void attachEntity(Sintoma entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Sintoma readEntity(Cursor cursor, int offset) {
        Sintoma entity = new Sintoma( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // patientId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // ambito
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // signo
            cursor.isNull(offset + 4) ? null : cursor.getShort(offset + 4) != 0 // activo
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Sintoma entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPatientId(cursor.getLong(offset + 1));
        entity.setAmbito(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setSigno(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setActivo(cursor.isNull(offset + 4) ? null : cursor.getShort(offset + 4) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Sintoma entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Sintoma entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Sintoma entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "sintomaList" to-many relationship of Patient. */
    public List<Sintoma> _queryPatient_SintomaList(long patientId) {
        synchronized (this) {
            if (patient_SintomaListQuery == null) {
                QueryBuilder<Sintoma> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.PatientId.eq(null));
                patient_SintomaListQuery = queryBuilder.build();
            }
        }
        Query<Sintoma> query = patient_SintomaListQuery.forCurrentThread();
        query.setParameter(0, patientId);
        return query.list();
    }

}
